### ISSUE TITLE
Request for package release

### ISSUE THREAD

**Issue by cezar06** [dotnet/smartcomponents#28]
I would like to request a package release for smartcomponents

**Comment by SteveSandersonMS** [comment]
We're regarding this repo as samples, so it's something you can use as inspiration or even to take code from to use in your own application. As such we won't be shipping supported packages from here. You might notice we've updated the usage instructions in the docs here to recommend adding the relevant code to your own source repo.

This is because most of the feedback we've had so far is that people want to customize things in a really detailed way, and the ultimate way to do that is to own the code yourself so you can make it behave any way you want. Hope that's OK.
